# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}

# When to find text on a page case-insensitively.
# Type: String
# Valid values:
#   - always: Search case-insensitively.
#   - never: Search case-sensitively.
#   - smart: Search case-sensitively if there are capital characters.
c.search.ignore_case = 'smart'

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#b9b9b9'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#101010'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#101010'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#a0a0a0'

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#101010'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#101010'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#101010'

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = '#252525'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#a0a0a0'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#a0a0a0'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#a0a0a0'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#8e8e8e'

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#b9b9b9'

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = '#101010'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#101010'

# Color gradient start for download text.
# Type: QtColor
c.colors.downloads.start.fg = '#101010'

# Color gradient start for download backgrounds.
# Type: QtColor
c.colors.downloads.start.bg = '#686868'

# Color gradient end for download text.
# Type: QtColor
c.colors.downloads.stop.fg = '#101010'

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = '#868686'

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = '#7c7c7c'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#101010'

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = '#a0a0a0'

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = '#b9b9b9'

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = '#b9b9b9'

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = '#b9b9b9'

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = '#101010'

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = '#101010'

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = '#7c7c7c'

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = '#7c7c7c'

# Foreground color of a warning message.
# Type: QssColor
c.colors.messages.warning.fg = '#101010'

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = '#747474'

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = '#747474'

# Foreground color of an info message.
# Type: QssColor
c.colors.messages.info.fg = '#b9b9b9'

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = '#101010'

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = '#101010'

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = '#b9b9b9'

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = '#101010'

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = '#101010'

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = '#a0a0a0'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#8e8e8e'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#101010'

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = '#101010'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = '#686868'

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = '#101010'

# Background color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.bg = '#868686'

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = '#101010'

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = '#525252'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#b9b9b9'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#101010'

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = '#b9b9b9'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#101010'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#101010'

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = '#747474'

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = '#101010'

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = '#686868'

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = '#686868'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#b9b9b9'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#7c7c7c'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#b9b9b9'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#868686'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#8e8e8e'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#747474'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#101010'

# Color gradient start for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.start = '#686868'

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = '#868686'

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = '#7c7c7c'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#525252'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#101010'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#b9b9b9'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#101010'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#525252'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#101010'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#101010'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#b9b9b9'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = 'Iosevka'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '16pt Iosevka'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = '16pt Iosevka'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '16pt Iosevka'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '16pt Iosevka'

# Font used for the hints.
# Type: Font
c.fonts.hints = '16pt Iosevka'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '16pt Iosevka'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '16pt Iosevka'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '16pt Iosevka'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '16pt Iosevka'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '16pt Iosevka'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '16pt Iosevka'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '16pt Iosevka'

# Bindings for normal mode
config.bind('zp', 'open -t https://getpocket.com/edit?url={url}')
