# Base {{{
set-window-option -g mode-keys vi
set -g default-terminal 'screen-256color'
set -g status on
set -g status-left ''
set -g status-right ''
set -g status-justify centre
set -g status-keys vi
set -g mouse off
set -g set-clipboard on
# }}}
# Bindings {{{
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'Space' send -X halfpage-down
bind-key -T copy-mode-vi 'Bspace' send -X halfpage-up
# }}}
# Colors {{{
set -g status-style "bg=black"
set -ag status-style "fg=white"
set -g message-command-style "fg=white"
set -ag message-command-style "bg=black"
set -g message-style "fg=white"
set -ag message-style "bg=black"
set -g mode-style "fg=white"
set -ag mode-style "bg=black"
set -g pane-border-style "bg=black"
set -ag pane-border-style "fg=black"
# }}}
# vim:foldmethod=marker:foldlevel=0
